# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- script: |
   az login --service-principal -u 457a2087-c8e9-4998-9ab6-fcecddada55d -p aKF8Q~h1eSmRhuOpdubRaOzaQk5J4TX2XEIaDcvf --tenant 1f4beacd-b7aa-49b2-aaa1-b8525cb257e0
  displayName: 'Login azure'

- script: |
   cd FDB-storage-app
   ls
   az acr build --image sonein:v$(Build.BuildId) --registry demoacrsc --file dockerfile .
  displayName: 'Build and push to registry'

- script: |
   az container update --resource-group myResourceGroup --name containersc --image demoacrsc.azurecr.io/sonein:v$(Build.BuildId) --registry-username prajwal11 --registry-password 7jYIp0ugnt4j0m+UEIcRq0KGW/goA9oKNPAWKCQWf/+ACRBT4bZE
   displayName: 'Update Container Instance'