# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- script: |
   az group create --name myResourceGroup2 --location eastus
   az acr create --resource-group myResourceGroup1 --name acrwhenin23 --sku Basic
  displayName: 'Build and Push Docker Image'

- script: |
   az acr build --image sonein:v1 --registry acrwhenin22 --file Dockerfile .
  displayName: 'push to registry'