# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- script: |
   docker build -t $(Build.Repository.Name):$(Build.BuildId) .
   docker login -u prajwal11 -p CVM6nsLsyiZehaEMB8d4uFg9TiogSRApTpidjTu8Az+ACRCqs9fE prajwal11.azurecr.io
   docker tag $(Build.Repository.Name):$(Build.BuildId) prajwal11.azurecr.io/sample/hello-norld:$(Build.BuildId)
   docker push prajwal11.azurecr.io/sample/hello-norld:$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- script: docker images
  displayName: 'List Docker Images'