name: Trigger auto deployment for demosccontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demosccontainerapp-AutoDeployTrigger-20abcf79-4fd9-4081-acbe-0ddfc4f53a52.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOSCCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: demoacrsc.azurecr.io
          registryUsername: ${{ secrets.DEMOSCCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOSCCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: demosccontainerapp
          resourceGroup: demo_storage_condition
          imageToBuild: demoacrsc.azurecr.io/demosccontainerapp:${{ github.sha }}
          

     

